apiVersion: v1
kind: Service
metadata:
  name: devops-app
  namespace: default
  labels:
    app: devops-app
spec:
  selector:
    app: devops-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
